zuul:
  routes:
    resource:
      path: /api/resource/**
      url: http://localhost:9000/api/resource/
    uaa:
      path: /uaa/**
      url: http://localhost:9999/uaa/
#    user:
#      path: /uaa/user
#      url: http://localhost:9999/uaa/user
#    token:
#      path: /uaa/token/*
#      url: http://localhost:9999/uaa/oauth/token
#    oauth:
#      path: /uaa/oauth/**
#      url: http://localhost:9999/uaa/oauth/**

spring:
  oauth2:
    sso:
      home:
        secure: false
        path: /,/**/*.html
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: http://localhost:9999/uaa/user
