zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000/api/resource/
    uaa:
      path: /uaa/**
      url: http://localhost:9999/uaa/

spring:
  oauth2:
    sso:
      home:
        secure: false
        path: /,/**/*.html
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: polymer-ui-server
      clientSecret: polymer-ui-secret
    resource:
      userInfoUri: http://localhost:9999/uaa/user
