#userInfoUri=https://uaa.cloudfoundry.com/userinfo
#checkTokenUrl=https://uaa.cloudfoundry.com/check_token
#accessTokenUri=https://uaa.cloudfoundry.com/oauth/token
#userAuthorizationUri=https://uaa.cloudfoundry.com/oauth/authorize
#approvalsUri=http://login.cloudfoundry.com/approvals
#treeUrlPattern=https://api.cloudfoundry.com/{type}
#dataUri=https://api.cloudfoundry.com/apps
#cloudFoundryLogoutUrl=http://uaa.cloudfoundry.com/logout.do

#Client ID: polymer-demo
#Client Secret: xxx